// Generated by RuleStringController.cs:Strings
$$WP.Strings.getNamespace("clinical.testresults").removeString("TestResultsSideBarText");
$$WP.Strings.getNamespace("clinical.testresults").addString("TestResultsSideBarText","");
